# POST http://localhost:3001/api/users
# Content-Type: application/json

# {
#     "name": "Tinh",
#     "email": "tinh@gmail.com",
#     "password": "1234567"
# }

GET http://localhost:3001/api/users
Content-type: application/json